apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 5044
    targetPort: beats
    protocol: TCP
    name: beats
  - port: 9600
    targetPort: monitoring
    protocol: TCP
    name: monitoring
  selector:
    app: logstash 