version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_gateway_auth_test
      POSTGRES_MULTIPLE_DATABASES: api_gateway_auth,api_gateway_auth_test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
