version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: api-gateway-auth-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-api_gateway_auth}
    ports:
      - '0.0.0.0:5436:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d api_gateway_auth']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  postgres_data:
