
ALTER TABLE IF EXISTS inventory_reservations
ADD COLUMN IF NOT EXISTS product_id UUID,
ADD COLUMN IF NOT EXISTS quantity INTEGER,
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS sku VARCHAR(100),
DROP COLUMN IF EXISTS reservation_id,
DROP COLUMN IF EXISTS warehouse_id;

ALTER TABLE IF EXISTS payment_info
DROP COLUMN IF EXISTS status_enum,
DROP COLUMN IF EXISTS status_str,
ADD COLUMN IF NOT EXISTS status VARCHAR(50);

ALTER TABLE IF EXISTS warehouses
ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255);

ALTER TABLE IF EXISTS inventory_items
ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2);

ALTER TABLE IF EXISTS shipping_info
ADD COLUMN IF NOT EXISTS status VARCHAR(50),
DROP COLUMN IF EXISTS status_str,
ADD COLUMN IF NOT EXISTS expected_delivery TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS actual_delivery TIMESTAMP WITH TIME ZONE;