
ALTER TABLE IF EXISTS inventory_reservations
ADD COLUMN IF NOT EXISTS product_id UUID,
ADD COLUMN IF NOT EXISTS quantity INTEGER,
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS sku VARCHAR(100),
DROP COLUMN IF EXISTS reservation_id,
DROP COLUMN IF EXISTS warehouse_id;

ALTER TABLE IF EXISTS payment_info
DROP COLUMN IF EXISTS status_enum,
DROP COLUMN IF EXISTS status_str,
ADD COLUMN IF NOT EXISTS status VARCHAR(50);

ALTER TABLE IF EXISTS warehouses
ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255);

ALTER TABLE IF EXISTS inventory_items
ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2);

ALTER TABLE IF EXISTS shipping_info
ADD COLUMN IF NOT EXISTS status VARCHAR(50),
DROP COLUMN IF EXISTS status_str,
ADD COLUMN IF NOT EXISTS expected_delivery TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS actual_delivery TIMESTAMP WITH TIME ZONE;


ALTER TABLE IF EXISTS inventory_items
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS category VARCHAR(100),
ADD COLUMN IF NOT EXISTS attributes JSONB,
ADD COLUMN IF NOT EXISTS quantity INTEGER,
ADD COLUMN IF NOT EXISTS overstock_threshold INTEGER,
ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER;


ALTER TABLE IF EXISTS inventory_transactions
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS inventory_reservations
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;