apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-auth
  namespace: default
  labels:
    app: api-gateway-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-auth
  template:
    metadata:
      labels:
        app: api-gateway-auth
    spec:
      containers:
      - name: api-gateway-auth
        image: caiotheodoro/api-gateway-auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /auth/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /auth/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-auth
  namespace: default
  labels:
    app: api-gateway-auth
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: api-gateway-auth 