apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

labels:
  - pairs:
      app: frontend-auth
      part-of: synkro-platform
      component: auth-ui
