apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-sync
  namespace: default
  labels:
    app: inventory-sync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-sync
  template:
    metadata:
      labels:
        app: inventory-sync
    spec:
      containers:
      - name: inventory-sync
        image: inventory-sync:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-sync
  namespace: default
  labels:
    app: inventory-sync
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  - port: 50051
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    app: inventory-sync 