apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ai-ml-predictions
- api-gateway-auth
- notification-service
- frontend
- elk-stack
- database
- ingress.yaml

namespace: default

commonLabels:
  part-of: synkro-platform 