apiVersion: v1
kind: Service
metadata:
  name: ai-ml-predictions
  namespace: default
  labels:
    app: ai-ml-predictions
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: ai-ml-predictions 