name: ai-ml-predictions
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  # Core Dependencies
  - fastapi=0.109.0
  - uvicorn=0.27.0
  - python-dotenv=1.0.0
  # Database and Caching
  - sqlalchemy=2.0.25
  - psycopg2=2.9.9
  - redis-py=5.0.1
  - alembic=1.13.1
  # ML Dependencies
  - numpy=1.24.4
  - pandas=1.5.3
  - scikit-learn=1.3.2
  - lightgbm=4.1.0
  - xgboost=2.0.3
  - pytorch::pytorch=2.1.2
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::cpuonly
  - mlflow=2.9.2
  # Monitoring and Logging
  - prometheus_client=0.19.0
  - python-json-logger=2.0.7
  - opentelemetry-api=1.21.0
  - opentelemetry-sdk=1.21.0
  # Testing
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - pytest-asyncio=0.23.3
  - httpx=0.26.0
  # Security
  - python-jose=3.3.0
  - passlib=1.7.4
  - bcrypt=4.1.2
  # Development
  - black=23.12.1
  - isort=5.13.2
  - flake8=7.0.0
  - mypy=1.8.0
  - pip:
    # Packages not available in conda or need specific versions
    - feast==0.34.1
    - pydantic>=2.5.2
    - pydantic-settings>=2.1.0
    - python-dotenv>=1.0.0 