apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ml-predictions
  namespace: default
  labels:
    app: ai-ml-predictions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-ml-predictions
  template:
    metadata:
      labels:
        app: ai-ml-predictions
    spec:
      containers:
      - name: ai-ml-predictions
        image: ai-ml-predictions:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-ml-predictions
  namespace: default
  labels:
    app: ai-ml-predictions
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: ai-ml-predictions 