apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 5601
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: kibana 