apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../

namespace: development

commonLabels:
  environment: development

patches:
- path: replicas-patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ai-ml-predictions
  path: patches/ai-ml-predictions-deployment-patch.yaml 