apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: http
    protocol: TCP
    name: http
  - port: 9300
    targetPort: transport
    protocol: TCP
    name: transport
  selector:
    app: elasticsearch 