apiVersion: v1
kind: Service
metadata:
  name: api-gateway-auth
  namespace: default
  labels:
    app: api-gateway-auth
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: api-gateway-auth 