version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: logistics-engine-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-logistics}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-logistics_password}
      POSTGRES_DB: ${POSTGRES_DB:-logistics_engine}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logistics -d logistics_engine"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: logistics-engine-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-logistics}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-logistics_password}
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: logistics-engine-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # Web UI
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
