apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../
- pdb.yaml

namespace: production

commonLabels:
  environment: production

patches:
- path: hpa-patch.yaml

images:
- name: ai-ml-predictions
  newName: ghcr.io/synkro/ai-ml-predictions
  newTag: v1.0.0
- name: frontend-dashboard
  newName: ghcr.io/synkro/frontend-dashboard
  newTag: v1.0.0
- name: frontend-auth
  newName: ghcr.io/synkro/frontend-auth
  newTag: v1.0.0
- name: frontend-landing
  newName: ghcr.io/synkro/frontend-landing
  newTag: v1.0.0
- name: notification-service
  newName: ghcr.io/synkro/notification-service
  newTag: v1.0.0 