apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-auth-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway-auth
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-ml-predictions-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-ml-predictions 