
ALTER TABLE IF EXISTS inventory_reservations
ADD COLUMN IF NOT EXISTS product_id UUID,
ADD COLUMN IF NOT EXISTS quantity INTEGER,
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS sku VARCHAR(100),
DROP COLUMN IF EXISTS reservation_id,
DROP COLUMN IF EXISTS warehouse_id;

ALTER TABLE IF EXISTS payment_info
DROP COLUMN IF EXISTS status_enum,
DROP COLUMN IF EXISTS status_str,
ADD COLUMN IF NOT EXISTS status VARCHAR(50);

ALTER TABLE IF EXISTS warehouses
ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255);